name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: No Docs
      run: "echo 'gem: --no-document' >> ~/.gemrc"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4
    - name: RubyGems Update
      run: gem update --system
    - name: Bundle Install
      run: bundle install
    - name: RSpec
      run: bundle exec rspec