name: CI
on: [push]
jobs:
  rails-5-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: No Docs
      run: "echo 'gem: --no-document' >> ~/.gemrc"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: RubyGems Update
      run: gem update --system
    - name: Install Appraisal
      run: gem install appraisal
    - name: Appraisal Install
      run: appraisal rails-5-2 bundle install
    - name: Run Tests
      run: appraisal rails-5-2 rspec
  rails-5-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: No Docs
      run: "echo 'gem: --no-document' >> ~/.gemrc"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: RubyGems Update
      run: gem update --system
    - name: Update Bundler
      run: gem update bundler
    - name: Install Appraisal
      run: gem install appraisal
    - name: Appraisal Install
      run: appraisal rails-5-1 bundle install
    - name: Run Tests
      run: appraisal rails-5-1 rspec
  rails-5-0:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: No Docs
      run: "echo 'gem: --no-document' >> ~/.gemrc"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4
    - name: RubyGems Update
      run: gem update --system
    - name: Install Appraisal
      run: gem install appraisal
    - name: Appraisal Install
      run: appraisal rails-5-0 bundle install
    - name: Run Tests
      run: appraisal rails-5-0 rspec
  rails-4-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: No Docs
      run: "echo 'gem: --no-document' >> ~/.gemrc"
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.4
    - name: RubyGems Update
      run: gem update --system
    - name: Install Appraisal
      run: gem install appraisal
    - name: Appraisal Install
      run: appraisal rails-4-2 bundle install
    - name: Run Tests
      run: appraisal rails-4-2 rspec
